name: BuildServer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: move to Server dir
      run:  cd SharpChatServer
    - name: Restore dependencies
      run: dotnet restore SharpChatServer.csproj
    - name: Build
      run: dotnet build SharpChatServer.csproj --no-restore
    - name: Test
      run: dotnet test SharpChatServer.csproj --no-build --verbosity normal
